<?php
// $Id$

/**
 * @file
 * Provides Views Implementation for the ApacheSolr Search Integration project
 * drupal.org/project/apachesolr
 */

/**
 * Implementation of hook_views_api().
 */
function apachesolr_views_views_api() {
  return array('api' => '3.0-dev');
}

/**
 * Implementation of hook_views_plugins_alter().
 */
function apachesolr_views_plugins_alter(&$plugins) {
  // Add apachesolr to the base of the node row plugin.
  $plugins['row']['node']['base'][] = 'apachesolr';
}

/**
 * Implementation of hook_theme().
 */
function apachesolr_views_theme() {
  return array(
    'apachesolr_views_term_titles' => array('term_names' => array()),
  );
}

/**
 * theme function for the term titles
 */
function theme_apachesolr_views_term_titles($term_names) {
  return "<span>" . implode('</span> + <span>', $term_names) . "</span>";
}
